### PR TITLE
added LLCC68 (Ebyte E220-400M30S 1W LoRa) support

### PR DESCRIPTION
**Pull request by sq2bka**
By accident bought E220 instead E22, but with updated RadioLib and simple edit of current code it is now possible to use it. Tested in a tracker for a few days.

### CODE REVIEW

**Comment by richonguzman** [comment]
hi!

great

so this new "type" of lora module runs in E220 instead of E22, right??

and Radiolibe does work with it without a problem?

**Comment by sq2bka** [comment]
Hi! 
Yes, E220 with LLCC68 looks like it's basically same pinout and same almost everything as SX1262, and even uses it's libs included to use parts of it. Only differences I found is spreading factor in range 5-11 instead of 7-12 and completely removed AFSK functionality from the chip. RadioLib is version you recently updated to, and with it it just works.

**Comment by richonguzman** [comment]
So you are using which SF? 11?

So there is no SF12 anymore with it?

**Comment by sq2bka** [comment]
Yeah, I completely forgot that by default in config there is setting for SF12 and SF9. Here we use SF9 as a standard mostly, so not sure how it affects the rest and if it's then worthy of making it officially supported, because chip apparently does not support SF12 by datasheet. I completely forgot about this .-.

**Comment by richonguzman** [comment]
> Yeah, I completely forgot that by default in config there is setting for SF12 and SF9. Here we use SF9 as a standard mostly, so not sure how it affects the rest and if it's then worthy of making it officially supported, because chip apparently does not support SF12 by datasheet. I completely forgot about this .-.

this is no problem at all with the previos caution notes :)

**Comment by sq2bka** [comment]
Sorry for the delay. Not sure if it's enough. If you could recommend any solution then I can add it. Do we need active SF check that will throw out info on init? I think just comments in lora utils should be enough

**Comment by richonguzman** [comment]
> Sorry for the delay. Not sure if it's enough. If you could recommend any solution then I can add it. Do we need active SF check that will throw out info on init? I think just comments in lora utils should be enough

sure, this should be enough (will try to add this this weekend ;) )

**Comment by sq2bka** [comment]
Hi there! Do I need to still modify something with new changes, or it's still in queue to add?

**Comment by richonguzman** [comment]
> Hi there! Do I need to still modify something with new changes, or it's still in queue to add?

hi,  i will add this for sure, I'll hope tonight to have free time... sorry for the delay

**Comment by richonguzman** [comment]
sorry for the delay, finally its been added ;)

**Comment by richonguzman** [comment]
let me know if we should add this also to igate as I saw you starting with it too !

**Pull request closed without merging**
