### PR TITLE
fast shutdown with multiClick

### PR DESCRIPTION
**Pull request by formtapez**
To quickly power off the tracker you now can triple-press the user button.

### CODE REVIEW

**Comment by formtapez** [comment]
After using this feature for one week now, i never want to live without that 😀 When leaving the car, you are not forced to hold the button for 5 secs - Nobody has the time for that 😂
Should be easy to merge...

**Comment by richonguzman** [comment]
I was reading all the code , how is the "three pushes" called? where is written it?

or was I missing this as the "OneButton" library?

**Comment by formtapez** [comment]
The 3-push-event is registered in LoRa_APRS_Tracker.cpp via userButton.attachMultiClick()
The function is already present in some library - that code is not from me, but it works great 😀

The exact line is here:
https://github.com/richonguzman/LoRa_APRS_Tracker/pull/73/commits/0859c00af7ed7fa2b9412fc57c625e41122fe65e#diff-84bd53ddfeb48acb76ec3558d4cd2ef05c2a5f6182d8b039c8ab4b93db5f90edR197

**Comment by formtapez** [comment]
Did you find it?

**Comment by formtapez** [comment]
Can we get this merged please?

**Comment by richonguzman** [comment]
sorry sorry, was waiting for mods on the lora functions to add this all 

but will add this sooner for you

**Review by richonguzman — APPROVED** [review]
ok

**Pull request merged**
