### PR TITLE
BLE TNC improvements

### PR DESCRIPTION
**Pull request by SQ2CPA**
1. Always send own beacon to TNC, that works like in Thomas DL9SAU software
2. Send all received packets to TNC without any filtering, TNC RX and TX must be transparent
3. AX.25 KISS functions refactor, copied from IGate software (we want unification for the same features in both IGate and Tracker repos)
4. Ignore own beacon from TNC. Important option when we are using APRSDroid and we have the same SSID but we don't want beacon from APRSDroid to be send to RF
5. TNC KISS incoming buffer and sending in 64 bytes chunks

These changes will allow integration with APRSDroid via BLE :)

### CODE REVIEW

**Comment by iw9grl** [comment]
This means finally we can use Heltec WT with BLE through AprsDroid ??? GREAT !!! :) :)

**Comment by SQ2CPA** [comment]
> This means finally we can use Heltec WT with BLE through AprsDroid ??? GREAT !!! :) :)

Yes of course with the latest version of APRSDroid because changes are also in progress there. The changes on the tracker software are more stylistic but also quite important to work properly with APRSDroid

**Comment by richonguzman** [comment]
ok then:

- Always send own beacon to TNC, that works like in Thomas DL9SAU software

done and tested OK over BLE and iOS.

- Send all received packets to TNC without any filtering, TNC RX and TX must be transparent

done and tested OK over BLE and iOS.

- AX.25 KISS functions refactor, copied from IGate software (we want unification for the same features in both IGate and Tracker repos)

NOTE at the bottom!

- Ignore own beacon from TNC. Important option when we are using APRSDroid and we have the same SSID but we don't want beacon from APRSDroid to be send to RF

....  this I did not get why or what.

- TNC KISS incoming buffer and sending in 64 bytes chunks

done and tested OK over BLE and iOS.


NOTE: all implemented in Tracker firmware BRANCH "BLE-reformat": 
1) killed ax25_utils and created kiss_utils.h/cpp
2) ble_utils and bluetooth_utils should call this KISS_Utils::functions and worked fine in BLE over iOS. Please test over regular BT (Classic) and Aprsdroid
3) used your proposal as it was pretty close to the KISS we used on other firmwares, and was used for BT classic in tracker firmware for a while and clearly was more elegant than my "stone-age" code for just BLE.

**Comment by richonguzman** [comment]
test and report

**Pull request closed without merging**
