### PR TITLE
Add Bluetooth + T-LoRa board + Fix AXP GPS register

### PR DESCRIPTION
**Pull request by valentintintin**
Hi ! This is my fork with few new features

- Add capability to use **GPS Bluetooth Serial connection** with [Share GPS Android App](https://play.google.com/store/apps/details?id=com.jillybunch.shareGPS&hl=fr&gl=US)
- Add capability to **send APRS messages** with [APRSDroid](https://aprsdroid.org/)
- Add board TTGO **T-Lora** V2.1.6 (menu show is listening because there isn't any button or GPS in this one)
- Add capability to **disable GPS** (for T-Beam when we use BT, we save a lot of battery)
- Fix bug in power_management : channel was for SX and not the GPS (AXP192_LDO2 != **AXP192_LDO3**)

Have a nice review :)

### CODE REVIEW

**Comment by Mane76** [comment]
Hello Valentin, this is a very interesting approach ! Thank you for sharing.
May I ask, is the send messaging capability limited to APRSDroid or is another app like Meshtasric also compatible ? Is it also possible to display the received messages on the mobile phone ?

BR
Manfred

**Comment by valentintintin** [comment]
Hi !

You can use the application APRS TX on IOS.
APRSDroid is the best for Android.

Meshtastic isn't compatible at all today. I'll see if I can join both projects in the future 🤔

Yes, on APRSDroid you will be able to chat on your phone, see messages and every frame received.

**Comment by Mane76** [comment]
Thank you for this promising infos, I will give it a try !

BR
Manfred

**Review by richonguzman — COMMENTED** [review]
yolo

**Review by richonguzman — APPROVED** [review]
yolo

**Comment by tk5ep** [comment]
I tried the  connection to APRSDroid.
I'm not sure what it should do ? I don't see anything happening.
Is the tracker sending its GPS position to the APRSDroid ?
Can you give some précisions ?
Thanks,

**Comment by valentintintin** [comment]
Do you have the bluetooth symbol at the top right of the screen every 5s ?
If yes you are connected to the app. Otherwise, pair it with your phone, set APRSDroid to use it and press "Start tracking" ("Commencer la localisation" in french).

If even with the symbol nothing happens, maybe it's the configuration of the smart-beaconing inside the app that you'll have to configure.

APRSDroid acts as a "master" so it's the app which sends frames to the tracker.
The tracker only send over BT all frames it hears

**Comment by tk5ep** [comment]
Hi Valentin,
Thanks for the answer.

Yes, I have paired the tracker and did set my phone in the APRSDroid parameters.
I never saw this blinking symbol. (you mean on top right of APRSDroid ?)

I thought that the Tracker acts as a TNC, and that it makes the connection from APRSDroid to the APRS network (via the LoRa radio). Not the reverse.

Sorry, but it's still unclear to me.

**Comment by valentintintin** [comment]
Patrick, You should see the symbol on the oled screen : [Video on Twitter](https://twitter.com/valentinF4HVV/status/1688931010522869760)

**Comment by tk5ep** [comment]
Ha ha ! We were not talking of the same screen !
I was talking of the APRSDroid. :-)
Yes, I have this sign.

**Comment by valentintintin** [comment]
Ok so the connection is good between them two.
It remains the APRSDroid side. Try to do like me with this video : [video.gif](https://github.com/richonguzman/LoRa_APRS_Tracker/assets/12508070/2a7c2866-f5e8-4953-b4fd-69a1dd138a40)

**Comment by tk5ep** [comment]
OK, it works now.  :-)

I sniffed on the 433.775 MHz to see what is transmitted.

The Tracker is used as a TNC and sends the phone GPS position to the APRS network via the LoRa modem.
At the same time, the Tracker sends its own position as well.
A bit confusing.

The connected tracker sends received beacons on 433.775 MHz to APRSDroid.

So, it seems to work as expected. Did I overlook something else ?

BTW, I've setup APRSDroid to send its positions at regular interval. But it's not really doing what I expected.
I didn't try the smatbeaconing for the moment.

**Comment by valentintintin** [comment]
Great news :)

Yes the tracker continues to send its position. It's why I've added a boolean `disableGps` in the JSON file to disable it.
You are ready now, there isn't anything else :)

Smartbeaconing works nicely.
For regular interval, set "Periodic position GPS/GSM Network" and set the minimum delay to 1 (minute). Set the minimum distance to 0 too

**Comment by tk5ep** [comment]
OK. Thanks.

APRSDroid I installed this morning, isn't stable on my phone. 
I often has a black screen and it screws up the phone.  :-(

**Comment by Mane76** [comment]
@tk5ep , you can also put the position mode in aprsdroid from "smartbeacon" to "manual", then you can use aprsdroid **purely for messaging**. Position will be purely done from ttgo.

**Pull request merged**
